name: LifeSnapAction
options:
  bundleIdPrefix: com.zll
targets:
  LifeSnapAction:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LifeSnapAction
        excludes:
          - Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.zll.lifesnapaction.dev
      INFOPLIST_FILE: LifeSnapAction/Info.plist
      GENERATE_INFOPLIST_FILE: "NO"
      ASHER_IS_IPHONE_TARGET: "YES"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      SWIFT_VERSION: "5.9"
      DEVELOPMENT_TEAM: "" # Leave empty for local building
